 language: node_js
 node_js:
 - 0.10
 before_install:
 - npm install -g dredd
script:
- mocha test/bootstrap.test.js test/unit/**/*.test.js
-./dredd
  services:
  - mongodb
  before_script:
  - mongo mydb_test --eval 'db.addUser("test", "test");'
